force-app/main/default/objects/Cat__c/Cat__c.object-meta.xml
<CustomObject>
    <label>Cat</label>
    <nameField>
        <label>Cat Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cats</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel__c/Hotel__c.object-meta.xml
<CustomObject>
    <label>Hotel</label>
    <nameField>
        <label>Hotel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/Visit__c.object-meta.xml
<CustomObject>
    <label>Visit</label>
    <nameField>
        <displayFormat>Visit-{00000}</displayFormat>
        <label>Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Visit__c/fields/Cat__c.field-meta.xml
<CustomField>
    <fullName>Cat__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Cat</label>
    <referenceTo>Cat__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <description>Last date of visit</description>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Hotel</label>
    <referenceTo>Hotel__c</referenceTo>
    <relationshipLabel>Visits</relationshipLabel>
    <relationshipName>Visits</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Visit__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <description>First day of visit</description>
    <label>Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/REST_CheckIn.cls
@RestResource(urlMapping='/v1/checkin')
global with sharing class REST_CheckIn{

    private static final Map<String,String> visitFieldMapping = new Map<String,String>{
        'Cat' => 'Cat__c', 
        'Hotel' => 'Hotel__c',
        'StartDate' => 'Start_Date__c',
        'EndDate' => 'End_Date__c'
    };


    @HttpPost
    global static void postVisit(){
        RestResponse res = RestContext.response;
        RestRequest req = RestContext.request;

        List<Map<String,String>> visitDataList;
        List<Visit__c> visitList2Insert = new List<Visit__c>();

        if(String.isNotBlank(req.requestBody.toString())){
            visitDataList = (List<Map<String,String>>)JSON.deserialize(req.requestBody.toString(), List<Map<String,String>>.class);
        }

        for(Map<String,String> visitData : visitDataList){
            Visit__c visit2Insert = createFilledVisit(visitData);
            visitList2Insert.add(visit2Insert);
        }

        try{
            insert visitList2Insert;
        } catch(Exception ex){
            System.debug(ex.getMessage());
        } 
    }


    public static Visit__c createFilledVisit(Map<String,String> sourceMap){
        
        Visit__c visit = new Visit__c(
            Cat__c = sourceMap.get('Cat'),
            Hotel__c = sourceMap.get('Hotel'),
            Start_Date__c = Date.valueOf(sourceMap.get('StartDate')),
            End_Date__c = Date.valueOf(sourceMap.get('EndDate'))
        );
        return visit;
    }


}